name: Java CI

on:
  push:
    branches: [ dev ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      IMAGE: docker-counter-api

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build app
        run: ./gradlew clean build
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Build image
        run: docker build -t $LOGIN/$IMAGE:latest -f Dockerfile .
      - name: Push image
        run: docker push $LOGIN/$IMAGE:latest
